#obstacle_range: 2.5
#raytrace_range: 3.0
footprint: [[0.6, 0.315], [0.6, -0.315], [-0.6, -0.315], [-0.6, 0.315]]
footprint_inflation: 0.1
#robot_radius: 0.6
inflation_radius: 0.7
max_obstacle_height: 0.9
min_obstacle_height: 0.0
observation_sources: scan
scan: {data_type: LaserScan, topic: /scan, marking: true, clearing: true, expected_update_rate: 0}
